heat_template_version: 2014-10-16 

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the instances
    default: mengyangyukey

  floating_net_id:
    type: string
    description: Network ID of external network
    default: 1370ce1f-1da6-4c11-a5c5-57b4d21dc82c
    constraints:
      - length: { min: 36, max: 36 }
        description: Network UUID's must be 36 characters long (including dashes)
      - allowed_pattern: '[a-f0-9\-]*'
        description: Network UUID's must be composed of hexadecimals and dashes

  instance_type:
    type: string
    description: Instance type for web and DB servers
    default: m1.small
    constraints:
      - allowed_values: [m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge]
        description: instance_type must be a valid instance type

  metadata:
    type: json
    description: stack id passed by the main template

resources:

  Myserver:
    type: OS::Nova::Server
    properties:
      image: ECE1548.OFLab
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      networks:
        - network: ece1548-net
      # See comment block at bottom regarding metadata
      metadata: { get_param: metadata }
      security_groups:
        - mengyangyu
        - default
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            
            sudo su
              apt-get update
              apt-get install apache2 php5-common libapache2-mod-php5 php5-cli git -y
              apt-get build-dep python-imaging -y
              apt-get install libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev -y
              pip install pillow
              git clone git://github.com/jessiyu/project /home/ubuntu/project
              chmod 777 /var/www/index.html
              chmod 777 /var/www/
              cp /var/www/index.html /var/www/index.html.cp
              mkdir /var/www/uploads
              mkdir /var/www/downloads
              chmod 777 /var/www/uploads
              chmod 777 /var/www/downloads
              cp /home/ubuntu/project/index.html /var/www/index.html
              cp /home/ubuntu/project/compress.php /var/www/compress.php
        
              service apache2 restart

  floatingIP:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: floating_net_id }

  floatingIPAssociation:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floatingIP }
      server_id: { get_resource: Myserver }

outputs:
  ServerURL:
    description: URL for Web server
    value:
      str_replace:
        template: http://host
        params:
          host: { get_attr: [floatingIP, floating_ip_address] }


